### PR TITLE
feat: add select db support

### PR DESCRIPTION
**Pull request by tangyang9464**
Signed-off-by: tangyang9464 <tangyang9464@163.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@tangyang9464 can you setup semantic-release first?

**Comment by tangyang9464** [comment]
> @tangyang9464 can you setup semantic-release first?

@hsluoyz But isn’t semantic-release already setup? Do you mean to fix the part below first?
image

**Comment by hsluoyz** [comment]
@tangyang9464 yeah, I saw it. But it is never tested.. (https://github.com/jcasbin/redis-adapter/releases) Let's give it a try.

**Pull request merged**
